### ISSUE TITLE
Rename Main Package

### ISSUE THREAD

**Issue by caldwella2** [cmpsc-481-s22-m1/PyPiCount#38]
Currently the name of our main package is src, but in order to make the program more user friendly we should change it to the name of the acutal program.

The DS_store is in a bad place in the code, we should either place it in a user-level git-ignore or project-level git-ignore

**Comment by RyanHiltyAllegheny** [comment]
Main package and folder have been updated and changed in the main file repository. This issue was fixed on January 31st, 2022.
